#!/bin/zsh
cd "$(dirname "$0")"
echo "正在打开飞书应用后台..."
echo "当前卡点：Bot ability is not activated."
echo "需要操作：启用机器人能力。"
echo ""
open "https://open.feishu.cn/app/cli_aaa3c5a0c1389bcf"
echo "打开后请按下面路径找："
echo ""
echo "应用功能 / 机器人 / 启用机器人"
echo "或：功能管理 / 机器人 / 添加能力 / 启用"
echo ""
echo "启用后如果提示发布版本，请创建版本并发布/启用。"
echo "完成后回来双击：发送测试消息.command"
echo ""
echo "按回车关闭窗口。"
read
